- name: install nginx
  hosts: web
  become: yes

  tasks:
    - name: Ensure nginx package is present
      apt:
        name: nginx
        state: present

    - name: Ensure nginx service is started
      service:
        name: nginx
        state: started

    - name: Ensure SELinux is set to enforcing mode
      lineinfile:
        dest: /var/www/html/index.html
        regexp: 'Hello world'
        line: <p><script>document.write(new Date().toLocaleDateString());</script></p>